### ISSUE TITLE
Allow user to customize symbolic in panel(inventory)

### ISSUE THREAD

**Issue by Endermanbugzjfc** [crnw-dev/IslandArchitect#1]
# Allow user to customize symbolic in InvMenu panel(inventory)
_Or saayyyyyy gudbye~~~~~~_

**Comment by callumrawlinson** [comment]
You want help?

**Comment by Endermanbugzjfc** [comment]
> You want help?

With the customize symbolic or the entire plugin?

**Comment by callumrawlinson** [comment]
you pick>

**Comment by Endermanbugzjfc** [comment]
> you pick>

Maybe not?

My codes are really mess, they are hard to read. 

Also I'm stuck at making the generator class since the skyblock plugins gets the island spawn position and chest position statically from the generator class, so it is impossible to make it return the correct position that is set in the island data (`Generator->getSettings()`). 

The only way is to change the positions at runtime and change the tile position after the island is created.

**Comment by Endermanbugzjfc** [comment]
# Feature added *(e8c7e13a9895acb12c1bca99fa54247262c72a7f)*
